# Site settings
title: vp's café
owner: Vishnu Padmanabhan
email: vp@vishnupadmanabhan.com
description: > # this means to ignore newlines until "baseurl:"
  neoelemento is a publication curated by Vishnu Padmanabhan. It is a collection of articles & tips.
disclaimer: >
  The content of this website is solely the opinion of the writer.
baseurl: "/articles" # the subpath of your site, e.g. /blog/
url: "http://vishnupadmanabhan.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
    style: compressed
gems:
  - jemoji
  - jekyll-paginate

permalink: /:title/
future: true
paginate: 12